# Generated by Django 5.1.4 on 2025-01-17 02:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gw", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="create_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="question",
            name="create_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
