# Generated by Django 5.1.4 on 2025-02-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gw", "0004_answer_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
